// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterCapacityListerExpansion allows custom methods to be added to
// ClusterCapacityLister.
type ClusterCapacityListerExpansion interface{}

// ClusterCapacityNamespaceListerExpansion allows custom methods to be added to
// ClusterCapacityNamespaceLister.
type ClusterCapacityNamespaceListerExpansion interface{}
