services:
- docker

cache:
  directories:
  - /var/lib/docker

env:
  global:
  - secure: "OMjn+5GtDBLYsOl5WvPrTHZ4nkcxTP9RsgD6vBDxaqec95qVw3ns1jczGaOMjRnLXU7H/8b+mA5HAC2ZcVRVyc1e+2JfPF/eR7RoeT7qJlE1sxOm5MTUpdknLboD9eO/JiuuSrW4OFjQTTeuBSCViOIxsap0JUhnGIWyYsECMxQKVXaQ4/RHv7mUy9Jua/+hABIKgvG52qWmj/A1/l+SahEtMNpWwFHfGmNuUExo+yQQ58zr6alkeQbhIsqx+IN9tC2liosk5z/SXh4AK0GyTdncnyEVaUZ2/ILA8FGqlceopE6oSXWb8uobaqkKNpQpLiUFCmOgAVglcTrPN1ofAc8Z1PDHst0ncEXBTQKkFF6jCfrNTK+guovjmatK+zqKeHwIY0kk+jsgfTEaR9L3RLvBPNo/gn4Tz+5t824fXIC1/b8OsnzNUn95SHkT+zWaT9QAlnjENR4PwI7Zjy8NCYzkllPFc/zrh4sxdVTXLfMmuUZ5y5j47oqD3hIqSYF0FzkOIaH/lnyhdOrk7zUVDa9XWcymsWMl0z+XefaQ7AiCsrYUy3w5tPNf6M8FVv+R6uDEqDkcPnrkJkjpKysPQDxF2iXKIEpCpU5PvzWTHrObYHRBGjHaHxcroOkDMZFrzu/1Yq9Z13nhEAqr+/NbaOOf73QOnIfDcIDGkYsLiEI="
  - secure: "f/Ubdt4/aRSuWpEkYUiT/UrpBKl5JVEVOw+mknMwCgOAynabYA/vFvbEWV8Fzw6OdDouro1Unbznd8vIDY2nzC2XpDXRZ/9qVd4BKLU4YI7LhRvK3kExxQM/o7doT0KcR85OUAsFjZ/L+w+Y1QzJ166jPIPaLPHgLMydZdM8kxIKguyRI4MO+kMFoYxu56aE5v66Foi+30K77bkn8rDdvzWveG5TMhdCAYxVU6iS+UwY5mwWynlgEi6cB4cUJg0x8tzRr64ZQ/glEeavLL7zSEUXoDDEwstg7GWrZ0/1CLMDD4D3FZhNsnS0B4cdX+7fkzdKkZTmAXpQvgj39IB30W0GKgdIIjCQL6c2O+lG3zQDCK/qAjcTcxYxySMFL5WPVEyGEvO+Pl3heDYJhq5PaP8TSlScjBpXgBrvzNqX0RTKq522tVV5NDVmbjyOV3llI+fKus4HRfRnXPwtFd856PcAdsxC/c3+hT7d0cCF889fwDqvVFnmaFq2dmMsDmM7hy8QGbO45fV4kYXSc+iDxgNvIkx7d/cO/Haab97NanXwvLzzqzqMtSKi8LGyvT5ugBbjUcge0ibmHb0Ly9zBQoC6xnphBH9EvnFqF+0x5vX71fT8L1/FLL6eRpRbMm4vW5WnucSQU93YznYWlPzyikcpYxahVh4A3o0IzpRS1GE="
before_script:
- TEMP='^release-(.*)$'
- '[[ "$TRAVIS_BRANCH" =~ $TEMP ]] ||:'

script:
- travis_wait docker build --tag supergiant/capacity:v${BASH_REMATCH[1]} .

after_success:
- if [[ "$TRAVIS_BRANCH" =~ $TEMP ]]; then docker login -u $DOCKER_USERNAME -p
  $DOCKER_PASSWORD ; docker push supergiant/capacity:v${BASH_REMATCH[1]}; fi
