// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/supergiant/capacity/pkg/client/clientset/versioned/typed/capacity/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCapacityV1 struct {
	*testing.Fake
}

func (c *FakeCapacityV1) ClusterCapacities(namespace string) v1.ClusterCapacityInterface {
	return &FakeClusterCapacities{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCapacityV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
