// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MachineType TODO: split string and resource representation
// swagger:model MachineType
type MachineType struct {

	// CPU
	CPU string `json:"cpu,omitempty"`

	// memory
	Memory string `json:"memory,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this machine type
func (m *MachineType) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MachineType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MachineType) UnmarshalBinary(b []byte) error {
	var res MachineType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
