{{ if .Values.userdata }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: capacity-service
  labels:
    app: capacity-service
data:
  userdata: {{ quote .Values.userdata }}
{{ end }}
