apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  name: capacity-service
  labels:
    app: capacity-service
spec:
  selector:
    app: capacity-service
  template:
    metadata:
      labels:
        app: capacity-service
    spec:
      containers:
        - name: capacity-service
          image: supergiant/capacity:v0.1
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/capacity-service/userdata
            subPath: userdata
          env:
          {{- range $key, $value := .Values.config }}
          - name: capacity_{{ $key }}
            {{- if typeIs "string" $value }}
            value: {{ quote (quote $value) }}
            {{- else if typeIs "<nil>" $value }}
            value: "null"
            {{- else }}
            value: {{ quote $value }}
            {{- end }}
          {{- end }}
          {{- range $key, $value := .Values.provider }}
          - name: capacity_provider_{{ $key }}
            {{- if typeIs "string" $value }}
            value: {{ quote (quote $value) }}
            {{- else if typeIs "<nil>" $value }}
            value: "null"
            {{- else }}
            value: {{ quote $value }}
            {{- end }}
          {{- end }}
          {{- range $index, $value := .Values.machineTypes }}
          - name: capacity_machineTypes_{{ $index }}
            {{- if typeIs "string" $value }}
            value: {{ quote (quote $value) }}
            {{- else if typeIs "<nil>" $value }}
            value: "null"
            {{- else }}
            value: {{ quote $value }}
            {{- end }}
          {{- end }}
          - name: EXTRA_ARGS
            value: --verbosity=debug
      volumes:
        - name: config-volume
          configMap:
            name: capacity-service
            optional: true
      restartPolicy: Always
