apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: capacity-service
  labels:
    kubernetes.io/cluster-service: "true"
    app: capacity-service
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: capacity-service
