// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/supergiant/capacity/pkg/capacityclient/models"
)

// GetWorkerReader is a Reader for the GetWorker structure.
type GetWorkerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWorkerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWorkerOK creates a GetWorkerOK with default headers values
func NewGetWorkerOK() *GetWorkerOK {
	return &GetWorkerOK{}
}

/*GetWorkerOK handles this case with default header values.

workerResponse contains a worker representation.
*/
type GetWorkerOK struct {
	Payload *models.Worker
}

func (o *GetWorkerOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/workers/{machineID}][%d] getWorkerOK  %+v", 200, o.Payload)
}

func (o *GetWorkerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Worker)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
