// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetWorkerParams creates a new GetWorkerParams object
// with the default values initialized.
func NewGetWorkerParams() *GetWorkerParams {
	var ()
	return &GetWorkerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkerParamsWithTimeout creates a new GetWorkerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkerParamsWithTimeout(timeout time.Duration) *GetWorkerParams {
	var ()
	return &GetWorkerParams{

		timeout: timeout,
	}
}

// NewGetWorkerParamsWithContext creates a new GetWorkerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkerParamsWithContext(ctx context.Context) *GetWorkerParams {
	var ()
	return &GetWorkerParams{

		Context: ctx,
	}
}

// NewGetWorkerParamsWithHTTPClient creates a new GetWorkerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkerParamsWithHTTPClient(client *http.Client) *GetWorkerParams {
	var ()
	return &GetWorkerParams{
		HTTPClient: client,
	}
}

/*GetWorkerParams contains all the parameters to send to the API endpoint
for the get worker operation typically these are written to a http.Request
*/
type GetWorkerParams struct {

	/*MachineID*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get worker params
func (o *GetWorkerParams) WithTimeout(timeout time.Duration) *GetWorkerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get worker params
func (o *GetWorkerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get worker params
func (o *GetWorkerParams) WithContext(ctx context.Context) *GetWorkerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get worker params
func (o *GetWorkerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get worker params
func (o *GetWorkerParams) WithHTTPClient(client *http.Client) *GetWorkerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get worker params
func (o *GetWorkerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMachineID adds the machineID to the get worker params
func (o *GetWorkerParams) WithMachineID(machineID string) *GetWorkerParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the get worker params
func (o *GetWorkerParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param machineID
	if err := r.SetPathParam("machineID", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
