// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListWorkersParams creates a new ListWorkersParams object
// with the default values initialized.
func NewListWorkersParams() *ListWorkersParams {

	return &ListWorkersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListWorkersParamsWithTimeout creates a new ListWorkersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListWorkersParamsWithTimeout(timeout time.Duration) *ListWorkersParams {

	return &ListWorkersParams{

		timeout: timeout,
	}
}

// NewListWorkersParamsWithContext creates a new ListWorkersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListWorkersParamsWithContext(ctx context.Context) *ListWorkersParams {

	return &ListWorkersParams{

		Context: ctx,
	}
}

// NewListWorkersParamsWithHTTPClient creates a new ListWorkersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListWorkersParamsWithHTTPClient(client *http.Client) *ListWorkersParams {

	return &ListWorkersParams{
		HTTPClient: client,
	}
}

/*ListWorkersParams contains all the parameters to send to the API endpoint
for the list workers operation typically these are written to a http.Request
*/
type ListWorkersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list workers params
func (o *ListWorkersParams) WithTimeout(timeout time.Duration) *ListWorkersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list workers params
func (o *ListWorkersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list workers params
func (o *ListWorkersParams) WithContext(ctx context.Context) *ListWorkersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list workers params
func (o *ListWorkersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list workers params
func (o *ListWorkersParams) WithHTTPClient(client *http.Client) *ListWorkersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list workers params
func (o *ListWorkersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListWorkersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
