// Code generated by go-swagger; DO NOT EDIT.

package workers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewUpdateWorkerParams creates a new UpdateWorkerParams object
// with the default values initialized.
func NewUpdateWorkerParams() *UpdateWorkerParams {
	var ()
	return &UpdateWorkerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWorkerParamsWithTimeout creates a new UpdateWorkerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateWorkerParamsWithTimeout(timeout time.Duration) *UpdateWorkerParams {
	var ()
	return &UpdateWorkerParams{

		timeout: timeout,
	}
}

// NewUpdateWorkerParamsWithContext creates a new UpdateWorkerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateWorkerParamsWithContext(ctx context.Context) *UpdateWorkerParams {
	var ()
	return &UpdateWorkerParams{

		Context: ctx,
	}
}

// NewUpdateWorkerParamsWithHTTPClient creates a new UpdateWorkerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateWorkerParamsWithHTTPClient(client *http.Client) *UpdateWorkerParams {
	var ()
	return &UpdateWorkerParams{
		HTTPClient: client,
	}
}

/*UpdateWorkerParams contains all the parameters to send to the API endpoint
for the update worker operation typically these are written to a http.Request
*/
type UpdateWorkerParams struct {

	/*MachineID*/
	MachineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update worker params
func (o *UpdateWorkerParams) WithTimeout(timeout time.Duration) *UpdateWorkerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update worker params
func (o *UpdateWorkerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update worker params
func (o *UpdateWorkerParams) WithContext(ctx context.Context) *UpdateWorkerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update worker params
func (o *UpdateWorkerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update worker params
func (o *UpdateWorkerParams) WithHTTPClient(client *http.Client) *UpdateWorkerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update worker params
func (o *UpdateWorkerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMachineID adds the machineID to the update worker params
func (o *UpdateWorkerParams) WithMachineID(machineID string) *UpdateWorkerParams {
	o.SetMachineID(machineID)
	return o
}

// SetMachineID adds the machineId to the update worker params
func (o *UpdateWorkerParams) SetMachineID(machineID string) {
	o.MachineID = machineID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWorkerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param machineID
	if err := r.SetPathParam("machineID", o.MachineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
