// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"

	v1 "github.com/supergiant/capacity/pkg/apis/capacity/v1"
	"github.com/supergiant/capacity/pkg/client/clientset/versioned/scheme"
)

type CapacityV1Interface interface {
	RESTClient() rest.Interface
	ClusterCapacitiesGetter
}

// CapacityV1Client is used to interact with features provided by the capacity.supergiant.io group.
type CapacityV1Client struct {
	restClient rest.Interface
}

func (c *CapacityV1Client) ClusterCapacities(namespace string) ClusterCapacityInterface {
	return newClusterCapacities(c, namespace)
}

// NewForConfig creates a new CapacityV1Client for the given config.
func NewForConfig(c *rest.Config) (*CapacityV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CapacityV1Client{client}, nil
}

// NewForConfigOrDie creates a new CapacityV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CapacityV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CapacityV1Client for the given RESTClient.
func New(c rest.Interface) *CapacityV1Client {
	return &CapacityV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CapacityV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
